name: Release

on:
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    environment: NUGET_ENV
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Setup dotnet SDK 8.0.x
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 8.0.x
      - name: Build and Test
        run: ./Build.ps1
        shell: pwsh
      - name: Push to NuGet
        env:
          NUGET_URL: ${{ secrets.NUGET_URL }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: ./Push.ps1
        shell: pwsh
      - name: Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifacts
          path: artifacts/**/*
      
